### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/php-client#15]
**Is your feature request related to a problem? Please describe.**
On a brand new VM `composer require arkecosystem/client php-http/guzzle6-adapter` doesn't install, it needed `mbstring`:
`- illuminate/support v5.7.9 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.`
`- illuminate/support v5.7.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.`
`- illuminate/support v5.7.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.`

After that I got PHP error:
`PHP Fatal error:  Uncaught Error: Class 'NumberFormatter' not found in /home/darknodeuser/temp/vendor/arkecosystem/client/src/Connection.php:105
Stack trace:
#0 /home/darknodeuser/temp/vendor/arkecosystem/client/src/Connection.php(77): ArkEcosystem\Client\Connection->api('Wallets')
#1 /home/darknodeuser/temp/work(14): ArkEcosystem\Client\Connection->__call('Wallets', Array)
#2 {main}
  thrown in /home/darknodeuser/temp/vendor/arkecosystem/client/src/Connection.php on line 105`

**Describe the solution you'd like**
Not sure the best solution, I just did this:
`sudo apt-get install php-mbstring php-intl`

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/php-client/commit/60c3975c4c9b319c7fdbe4bce2f5b0afa43c7253
